definitions:
  model.User:
    properties:
      creator:
        type: string
      dateCreated:
        type: string
      email:
        type: string
      id:
        type: string
      isAdmin:
        type: boolean
      lastUpdated:
        type: string
      modifier:
        type: string
      password:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  model.Validation:
    properties:
      valid:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/login:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Perform login
  /api/v1/register:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Register user
  /api/v1/user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Get information of current user
  /api/v1/validate:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Validation'
            type: array
        "403":
          description: Forbidden
          schema:
            type: string
      summary: Validate token
swagger: "2.0"
