# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "github-actions"
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "daily"
  # Disable version updates for guthub-actions dependencies
  open-pull-requests-limit: 0

- package-ecosystem: "npm" # See documentation for possible values
  directory: "/frontend" # Location of package manifests
  schedule:
    interval: "daily"
  # Disable version updates for npm dependencies
  open-pull-requests-limit: 0

- package-ecosystem: "gomod" # See documentation for possible values
  directory: "/print" # Location of package manifests
  schedule:
    interval: "daily"
  # Disable version updates for go dependencies
  open-pull-requests-limit: 0

- package-ecosystem: "gomod" # See documentation for possible values
  directory: "/core" # Location of package manifests
  schedule:
    interval: "daily"
  # Disable version updates for go dependencies
  open-pull-requests-limit: 0

- package-ecosystem: "gomod" # See documentation for possible values
  directory: "/auth" # Location of package manifests
  schedule:
    interval: "daily"
  # Disable version updates for go dependencies
  open-pull-requests-limit: 0
