# https://cloud.google.com/appengine/docs/standard/python/getting-started/hosting-a-static-website

runtime: python39

handlers:
- url: /static/(.*)
  static_files: build/static/\1
  upload: build/static/(.*)

- url: /favicon.ico
  static_files: build/favicon.ico
  upload: build/favicon.ico

- url: /asset-manifest.json
  static_files: build/asset-manifest.json
  upload: build/asset-manifest.json

- url: /manifest.json
  static_files: build/manifest.json
  upload: build/manifest.json

- url: /(.*)
  static_files: build/index.html
  upload: build/index.html
