definitions:
  model.Maker:
    properties:
      name:
        type: string
    type: object
  model.Melody:
    properties:
      melody:
        type: string
    type: object
  model.Song:
    properties:
      arrangers:
        items:
          $ref: '#/definitions/model.Maker'
        type: array
      composers:
        items:
          $ref: '#/definitions/model.Maker'
        type: array
      creator:
        type: string
      dateCreated:
        type: string
      deleted:
        type: boolean
      extraInfo:
        type: string
      id:
        type: string
      lastUpdated:
        type: string
      lyricists:
        items:
          $ref: '#/definitions/model.Maker'
        type: array
      melody:
        $ref: '#/definitions/model.Melody'
      modifier:
        type: string
      tags:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      title:
        type: string
      verses:
        items:
          $ref: '#/definitions/model.Verse'
        type: array
    type: object
  model.Tag:
    properties:
      tag:
        type: string
    type: object
  model.Verse:
    properties:
      lyrics:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/song:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Song'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create song
  /api/v1/song/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Song'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get single song
    put:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Song'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update song
  /api/v1/songs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Song'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all songs
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Song'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create multiple songs at once
  /api/v1/songs/updated/{time}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Song'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get updated songs
swagger: "2.0"
