name: sss-auth

on:
  pull_request:
    paths:
      - "auth/**"
      - ".github/workflows/auth.yml"
      - ".github/workflows/go_cloud_run.yml"
  push:
    branches:
      - main

jobs:
  go_cloud_run:
    uses: ./.github/workflows/go_cloud_run.yml
    with:
      application-name: auth
    secrets: inherit
