name: sss-core

on:
  pull_request:
    paths:
      - "core/**"
      - ".github/workflows/core.yml"
  push:
    branches:
      - main

jobs:
  go_cloud_run:
    uses: ./.github/workflows/go_cloud_run.yml
    with:
      application-name: core
    secrets: inherit
