name: sss-core

on:
  pull_request:
    paths:
      - "core/**"
      - ".github/workflows/core.yml"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./core

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Set up golang
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # tag=v3
        with:
          go-version: '1.16'

      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          make ensure
          make test

      - name: Build
        run: |
          make build

  deploy-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    needs: test-build
    environment:
      name: PR-${{ github.event.pull_request.number }}-core
      url: ${{ steps.deploy_review.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@8d125895b958610ec414ca4dae010257eaa814d3 # tag=v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy review
        id: deploy_review
        uses: google-github-actions/deploy-appengine@e93940cb8e265ec9024aec36ecd56b794b8192e7
        with:
          working_directory: ./core
          version: pr-${{ github.event.pull_request.number }}
          promote: false

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push'
    environment:
      name: Production-core
      url: ${{ steps.deploy_prod.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@8d125895b958610ec414ca4dae010257eaa814d3 # tag=v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy production
        id: deploy_prod
        uses: google-github-actions/deploy-appengine@e93940cb8e265ec9024aec36ecd56b794b8192e7
        with:
          working_directory: ./core
          version: ${{ github.sha }}
          promote: true
