name: sss-frontend

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"


defaults:
  run:
    working-directory: ./frontend

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

  deploy-test:
    env:
      REACT_APP_BACKEND_API_BASE_URL: https://api-dot-sitsitsit-dev.ey.r.appspot.com
      REACT_APP_PRINT_API_BASE_URL: https://print-dot-sitsitsit-dev.ey.r.appspot.com
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: marceloprado/has-changed-path@0ffbcfc95a9a2976ba454d8e8687bb49f989f721 # v1.0
        id: changed-core
        with:
          paths: core .github/workflows/core.yml

      - uses: marceloprado/has-changed-path@0ffbcfc95a9a2976ba454d8e8687bb49f989f721 # v1.0
        id: changed-print
        with:
          paths: print .github/workflows/print.yml

      - name: Set PR core URL
        if: steps.changed-core.outputs.changed == 'true'
        run: |
          echo "REACT_APP_BACKEND_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-api-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Set PR print URL
        if: steps.changed-print.outputs.changed == 'true'
        run: |
          echo "REACT_APP_PRINT_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-print-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Deploy review
        uses: google-github-actions/deploy-appengine@32c708ac578033217aed2f2822d5ddd60999612e #0.3.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./frontend
          version: pr-${{ github.event.pull_request.number }}
          promote: false
