name: sss-frontend

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  push:
    branches:
      - main


defaults:
  run:
    working-directory: ./frontend

env:
  REACT_APP_BACKEND_API_BASE_URL: https://api-dot-sitsitsit-dev.ey.r.appspot.com
  REACT_APP_PRINT_API_BASE_URL: https://print-dot-sitsitsit-dev.ey.r.appspot.com
  REACT_APP_AUTH_API_BASE_URL: https://auth-dot-sitsitsit-dev.ey.r.appspot.com

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: |
          yarn

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

  deploy-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    needs: test-build
    environment:
      name: PR-${{ github.event.pull_request.number }}
      url: ${{ steps.deploy_review.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
        with:
          fetch-depth: 0

      - uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-core
        with:
          paths: core .github/workflows/core.yml

      - uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-print
        with:
          paths: print .github/workflows/print.yml

      - uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-auth
        with:
          paths: auth .github/workflows/auth.yml

      - name: Set PR core URL
        if: steps.changed-core.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_BACKEND_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-api-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Set PR print URL
        if: steps.changed-print.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_PRINT_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-print-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Set PR auth URL
        if: steps.changed-auth.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_AUTH_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-auth-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@8d125895b958610ec414ca4dae010257eaa814d3 # tag=v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy review
        id: deploy_review
        uses: google-github-actions/deploy-appengine@e93940cb8e265ec9024aec36ecd56b794b8192e7
        with:
          working_directory: ./frontend
          version: pr-${{ github.event.pull_request.number }}
          promote: false

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push'
    environment:
      name: Production
      url: ${{ steps.deploy_prod.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@8d125895b958610ec414ca4dae010257eaa814d3 # tag=v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy production
        id: deploy_prod
        uses: google-github-actions/deploy-appengine@e93940cb8e265ec9024aec36ecd56b794b8192e7
        with:
          working_directory: ./frontend
          version: ${{ github.sha }}
          promote: true
