name: sss-frontend

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  push:
    branches:
      - main


defaults:
  run:
    working-directory: ./frontend

env:
  REACT_APP_BACKEND_API_BASE_URL: https://api-dot-sitsitsit-dev.ey.r.appspot.com
  REACT_APP_PRINT_API_BASE_URL: https://print-dot-sitsitsit-dev.ey.r.appspot.com

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

  deploy-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test-build
    environment:
      name: PR-${{ github.event.pull_request.number }}
      url: ${{ steps.deploy_review.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: marceloprado/has-changed-path@0ffbcfc95a9a2976ba454d8e8687bb49f989f721 # v1.0
        id: changed-core
        with:
          paths: core .github/workflows/core.yml

      - uses: marceloprado/has-changed-path@0ffbcfc95a9a2976ba454d8e8687bb49f989f721 # v1.0
        id: changed-print
        with:
          paths: print .github/workflows/print.yml

      - name: Set PR core URL
        if: steps.changed-core.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_BACKEND_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-api-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Set PR print URL
        if: steps.changed-print.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_PRINT_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}-dot-print-dot-sitsitsit-dev.ey.r.appspot.com" >> $GITHUB_ENV

      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Deploy review
        id: deploy_review
        uses: google-github-actions/deploy-appengine@e3009e47609565a194033fbac6b6df2fd71fb6bf #0.4.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./frontend
          version: pr-${{ github.event.pull_request.number }}
          promote: false

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push'
    environment:
      name: Production
      url: ${{ steps.deploy_prod.outputs.url }}
    steps: 
      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Deploy production
        id: deploy_prod
        uses: google-github-actions/deploy-appengine@e3009e47609565a194033fbac6b6df2fd71fb6bf #0.4.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./frontend
          version: ${{ github.sha }}
          promote: true
