name: sss-frontend

on:
  push:
    paths:
      - "frontend/**"

defaults:
  run:
    working-directory: ./frontend

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: |
          yarn

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build
