name: sss-frontend

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  push:
    branches:
      - main


defaults:
  run:
    working-directory: ./frontend

env:
  REACT_APP_BACKEND_API_BASE_URL: https://core-edzfduyf6q-lz.a.run.app
  REACT_APP_PRINT_API_BASE_URL: https://print-edzfduyf6q-lz.a.run.app
  REACT_APP_AUTH_API_BASE_URL: https://auth-edzfduyf6q-lz.a.run.app

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        run: |
          yarn

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

  deploy-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor != 'renovate[bot]'
    needs: test-build
    environment:
      name: PR-${{ github.event.pull_request.number }}
      url: ${{ steps.deploy_review.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - uses: marceloprado/has-changed-path@df1b7a3161b8fb9fd8c90403c66a9e66dfde50cb # v1.0.1
        id: changed-core
        with:
          paths: core .github/workflows/core.yml

      - uses: marceloprado/has-changed-path@df1b7a3161b8fb9fd8c90403c66a9e66dfde50cb # v1.0.1
        id: changed-print
        with:
          paths: print .github/workflows/print.yml

      - uses: marceloprado/has-changed-path@df1b7a3161b8fb9fd8c90403c66a9e66dfde50cb # v1.0.1
        id: changed-auth
        with:
          paths: auth .github/workflows/auth.yml

      - name: Set PR core URL
        if: steps.changed-core.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_BACKEND_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}---core-edzfduyf6q-lz.a.run.app" >> $GITHUB_ENV

      - name: Set PR print URL
        if: steps.changed-print.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_PRINT_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}---print-edzfduyf6q-lz.a.run.app" >> $GITHUB_ENV

      - name: Set PR auth URL
        if: steps.changed-auth.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: |
          echo "REACT_APP_AUTH_API_BASE_URL=https://pr-${{ github.event.pull_request.number }}---auth-edzfduyf6q-lz.a.run.app" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy review
        id: deploy_review
        uses: google-github-actions/deploy-appengine@54d5fc7167ec790eb0233905e3cef384221b4619 # v3.0.1
        with:
          working_directory: ./frontend
          version: pr-${{ github.event.pull_request.number }}
          promote: false

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push'
    environment:
      name: Production
      url: ${{ steps.deploy_prod.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Build UI
        run: |
          yarn
          yarn build

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy production
        id: deploy_prod
        uses: google-github-actions/deploy-appengine@54d5fc7167ec790eb0233905e3cef384221b4619 # v3.0.1
        with:
          working_directory: ./frontend
          version: ${{ github.sha }}
          promote: true
