name: sss-print

on:
  pull_request:
    paths:
      - "print/**"
      - ".github/workflows/print.yml"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./print

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Set up golang
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # tag=v2
        with:
          go-version: '1.16'

      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          make ensure
          make test

      - name: Build
        run: |
          make build

  deploy-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test-build
    environment:
      name: PR-${{ github.event.pull_request.number }}-print
      url: ${{ steps.deploy_review.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Deploy review
        id: deploy_review
        uses: google-github-actions/deploy-appengine@e3009e47609565a194033fbac6b6df2fd71fb6bf #0.4.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./print
          version: pr-${{ github.event.pull_request.number }}
          promote: false

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push'
    environment:
      name: Production-print
      url: ${{ steps.deploy_prod.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2

      - name: Deploy production
        id: deploy_prod
        uses: google-github-actions/deploy-appengine@e3009e47609565a194033fbac6b6df2fd71fb6bf #0.4.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          working_directory: ./print
          version: ${{ github.sha }}
          promote: true
