name: sss-print

on:
  pull_request:
    paths:
      - "print/**"
      - ".github/workflows/print.yml"
      - ".github/workflows/go_cloud_run.yml"
  push:
    branches:
      - main

jobs:
  go_cloud_run:
    uses: ./.github/workflows/go_cloud_run.yml
    with:
      application-name: print
    secrets: inherit
