name: sss-print

on:
  pull_request:
    paths:
      - "print/**"
      - ".github/workflows/print.yml"

defaults:
  run:
    working-directory: ./print

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          make ensure
          make test

      - name: Build
        run: |
          make build
