name: Stop Review
on:
  pull_request:
    types: [closed]

jobs:
  stop_review:
    runs-on: ubuntu-latest
    name: Stop Review
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@daadedc81d5f9d3c06d2c92f49202a3cc2b919ba # 0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Remove review version
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: gcloud app versions delete pr-${{ github.event.pull_request.number }} -q

      - name: Disable frontend review environment
        uses: strumwolf/delete-deployment-environment@45c821e46baa405e25410700fe2e9643929706a0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-${{ github.event.pull_request.number }}
          onlyRemoveDeployments: true

      - name: Disable print review environment
        uses: strumwolf/delete-deployment-environment@45c821e46baa405e25410700fe2e9643929706a0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-${{ github.event.pull_request.number }}-print
          onlyRemoveDeployments: true

      - name: Disable core review environment
        uses: strumwolf/delete-deployment-environment@45c821e46baa405e25410700fe2e9643929706a0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-${{ github.event.pull_request.number }}-core
          onlyRemoveDeployments: true