name: Stop Review
on:
  pull_request:
    types: [closed]

env:
  IMAGE_NAME_PREFIX: europe-north1-docker.pkg.dev/sitsitsit-dev/sss/

jobs:
  stop_review:
    if:  github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    name: Stop Review
    steps:
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@8d125895b958610ec414ca4dae010257eaa814d3 # tag=v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Untag PR environment images
        run: |
          gcloud artifacts docker tags delete ${IMAGE_NAME_PREFIX}print:pr-${{ github.event.pull_request.number }} -q || echo "Nothing to untag"
          gcloud artifacts docker tags delete ${IMAGE_NAME_PREFIX}auth:pr-${{ github.event.pull_request.number }} -q || echo "Nothing to untag"
          gcloud artifacts docker tags delete ${IMAGE_NAME_PREFIX}core:pr-${{ github.event.pull_request.number }} -q || echo "Nothing to untag"

      - name: Remove review revisions
        run: |
          gcloud run revisions list --region europe-north1 --format json |  jq -r '.[] | select(.metadata.annotations."client.knative.dev/user-image" | contains("pr-${{ github.event.pull_request.number }}")) | .metadata.name' | xargs -n1 gcloud run revisions delete --region europe-north1 -q
          gcloud app versions delete pr-${{ github.event.pull_request.number }} -q

      - name: Disable frontend review environment
        uses: strumwolf/delete-deployment-environment@45c821e46baa405e25410700fe2e9643929706a0 # tag=v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-${{ github.event.pull_request.number }}
          onlyRemoveDeployments: true

      - name: Disable print review environment
        uses: strumwolf/delete-deployment-environment@45c821e46baa405e25410700fe2e9643929706a0 # tag=v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-${{ github.event.pull_request.number }}-print
          onlyRemoveDeployments: true

      - name: Disable core review environment
        uses: strumwolf/delete-deployment-environment@45c821e46baa405e25410700fe2e9643929706a0 # tag=v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-${{ github.event.pull_request.number }}-core
          onlyRemoveDeployments: true
